defaults:
  - _self_
  - task@_global_: quadruped_walk
  - override hydra/launcher: submitit_local

# task settings
frame_stack: 3
action_repeat: 2
discount: 0.99
# train settings
num_seed_frames: 4000
# eval
eval_every_frames: 10000
num_eval_episodes: 5
# snapshot
save_snapshot: true
# replay buffer
replay_buffer_size: 500000
replay_buffer_num_workers: 2
nstep: 3
batch_size: 256
# misc
seed: 1
device: cuda
save_video: true
save_train_video: false
use_tb: false
# experiment
experiment: exp
# agent
lr: 1e-4
feature_dim: 50
agent:
  _target_: drqv2.DrQV2Agent
  img_shape: ??? # to be specified later
  state_shape: ???
  action_shape: ??? # to be specified later
  max_actions: ???
  joint_indexes: ???
  device: ${device}
  lr: ${lr}
  critic_target_tau: 0.01
  update_every_steps: 2
  use_tb: ${use_tb}
  num_expl_steps: 2000
  hidden_dim: 1024
  feature_dim: ${feature_dim}
  stddev_schedule: ${stddev_schedule}
  stddev_clip: 0.3
  robot_name: ???
  experiment_type: none
  controller_iterations: ???
env_override:
  control_freq: ${action_repeat}
  controller_config_file: 'torque' # default to torque (no controller)
hydra:
  run:
    dir: /scratch/jhansen/DH22/${task_name}_${agent.experiment_type}_${env_override.control_freq}_${env_override.controller_config_file}/seed_${seed}/${now:%Y-%m-%d_%H-%M-%S}/
  sweep:
    dir: /scratch/jhansen/DH22/${task_name}_${agent.experiment_type}_${env_override.control_freq}_${env_override.controller_config_file}/seed_${seed}/${now:%Y-%m-%d_%H-%M-%S}/
    subdir: ${hydra.job.num}
  launcher:
    timeout_min: 4300
    cpus_per_task: 4
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
    submitit_folder: /scratch/jhansen/DH22/${task_name}_${agent.experiment_type}_${env_override.control_freq}_${env_override.controller_config_file}/${task_name}/${now:%Y-%m-%d_%H-%M-%S}/.slurm
