defaults:
  - _self_
  - task@_global_: robosuite_can
  - override hydra/launcher: submitit_local

# task settings

frame_stack: 3
action_repeat: 1
discount: 0.99
# train settings
num_seed_frames: 5000
#num_seed_frames: 600
# eval
eval_every_frames: 10000
num_eval_episodes: 1
# snapshot
save_snapshot: true
# replay buffer
replay_buffer_size: 500000
replay_buffer_num_workers: 2
nstep: 3
batch_size: 512
# misc
seed: 1
device: cuda
save_video: true
save_train_video: false
use_tb: true
# experiment
experiment: exp
# agent
lr: 1e-4
feature_dim: 50

agent:
  _target_: drqv2.DrQV2Agent
  obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  max_action: ??? # to be specified later
  device: ${device}
  lr: ${lr}
  critic_target_tau: 0.01
  update_every_steps: 2
  use_tb: ${use_tb}
  num_expl_steps: 2000
  hidden_dim: 1024
  feature_dim: ${feature_dim}
  stddev_schedule: ${stddev_schedule}
  stddev_clip: 0.3
  use_kinematic_loss: 0
  kine_weight: 1
  robot_name: ??? # to be specified later

hydra:
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${hydra.job.override_dirname}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${agent_cfg.experiment}
    subdir: ${hydra.job.num}
  launcher:
    timeout_min: 4300
    cpus_per_task: 2
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
    submitit_folder: ./exp/${now:%Y.%m.%d}/${now:%H%M%S}_${agent_cfg.experiment}/.slurm
